### ISSUE TITLE
Flexit Vario Wi-Fi fan

### ISSUE THREAD

**Issue by Tom-ahawk** [ynsgnr/blauberg-assistant#2]
Just a headsup. Your integration works with the Flexit  Vario fan also.

The integration toggle switch, is it only for turning the unit it self (not the fan) on/off?

What about the fans booster functionality, to turn on/off the fan speed 100%? I cant see your integration haveing this?
If you are able to implement the boost on/off, HA can then use this in an automation for additional fan functionality.
Attached is the HEX-documentation (and for boosting) for the fan.

Cheers, Tom
![image](https://github.com/user-attachments/assets/2e4945f3-9c06-4467-a0de-1014d1c82a9a)

[Blauberg.Smart.Wi-Fi.-.Smart.Home.pdf](https://github.com/user-attachments/files/18246360/Blauberg.Smart.Wi-Fi.-.Smart.Home.pdf)

**Comment by ynsgnr** [comment]
Boost functionality is not implemented since Fan should have speed control as well. You can set the speed to 100% instead. I don't know why your fan doesn't have the speed control available, feel free to add it with a PR

**Comment by Tom-ahawk** [comment]
Yes, you can set the fan speed to 100% (or less). So when the fan starts automatically the speed will be max (or less). 

The booster functionality is a separat functionality . In the app you can turn the fan on manually , the fan will run at 100% for 5 minutes. And you can hit the button again for stopping the fan before the 5 minutes have past. A useful functionality if you want the ventilate the room manually. 

This function would be nice to also have in your HA-integration. A button to turn the booster on/off. 

Example, your fan is in your bathroom. After doing number 2, the bathroom smells like $^[§≠$]5[${£<|}£{. Then you can hit the booster button….

![Image](https://github.com/user-attachments/assets/c8f91fad-f6e7-45dc-8a0f-075fd704ca50)

**Comment by ynsgnr** [comment]
> Yes, you can set the fan speed to 100% (or less). So when the fan starts automatically the speed will be max (or less).
> 
> The booster functionality is a separat functionality . In the app you can turn the fan on manually , the fan will run at 100% for 5 minutes. And you can hit the button again for stopping the fan before the 5 minutes have past. A useful functionality if you want the ventilate the room manually.
> 
> This function would be nice to also have in your HA-integration. A button to turn the booster on/off.
> 
> Example, your fan is in your bathroom. After doing number 2, the bathroom smells like [ § ≠ ]5[${£<|}£{. Then you can hit the booster button….
> 
> ![Image](https://github.com/user-attachments/assets/c8f91fad-f6e7-45dc-8a0f-075fd704ca50)

If you can control the fan speed, you can do this with HA automations and helpers, no implementation needed for a custom button

Go to http://{your-home-assistant-address}/config/helpers
Add Helper
Button


And then some automation like this:
```
description: ""
mode: single
triggers:
  - trigger: state
    entity_id:
      - input_button.fan_boost
conditions: []
actions:
  - action: fan.set_percentage
    metadata: {}
    data:
      percentage: 100
    target:
      entity_id: fan.bathroom
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: fan.set_percentage
    metadata: {}
    data:
      percentage: 25
    target:
      entity_id: fan.bathroom

```
